---
- name: Copy Configuration
  template:
    src: haproxy.cfg.j2
    dest:
      /etc/haproxy/haproxy.cfg
  register: config

- name: HAProxy check config
  command: haproxy -c -f /etc/haproxy/haproxy.cfg
  when: config.changed
  notify:
    - reload haproxy
