---
- name: Copy Configuration
  template:
    src: haproxy.conf.j2
    dest:
      /etc/haproxy/haproxy.conf
  register: config

- name: HAProxy check config
  command: haproxy -c -f /etc/haproxy/haproxy.conf
  when: config.changed
  notify:
    - reload haproxy
